#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msrestazure
Version  : 0.6.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/a3/a8/9c97984f706491c47fd30b113cf0ecc90ad6e61d86d37cd3ca05d2cb3444/msrestazure-0.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a3/a8/9c97984f706491c47fd30b113cf0ecc90ad6e61d86d37cd3ca05d2cb3444/msrestazure-0.6.0.tar.gz
Summary  : AutoRest swagger generator Python client runtime. Azure-specific module.
Group    : Development/Tools
License  : MIT
Requires: msrestazure-python = %{version}-%{release}
Requires: msrestazure-python3 = %{version}-%{release}
Requires: adal
Requires: msrest
BuildRequires : adal
BuildRequires : buildreq-distutils3
BuildRequires : msrest

%description
===============================================

%package python
Summary: python components for the msrestazure package.
Group: Default
Requires: msrestazure-python3 = %{version}-%{release}

%description python
python components for the msrestazure package.


%package python3
Summary: python3 components for the msrestazure package.
Group: Default
Requires: python3-core

%description python3
python3 components for the msrestazure package.


%prep
%setup -q -n msrestazure-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545578117
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
