#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msrestazure
Version  : 0.6.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/16/5b/fcd41fec16a8e6c6bea245132aef35f148fc549401c7f82ad59e57eacdd1/msrestazure-0.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/5b/fcd41fec16a8e6c6bea245132aef35f148fc549401c7f82ad59e57eacdd1/msrestazure-0.6.1.tar.gz
Summary  : AutoRest swagger generator Python client runtime. Azure-specific module.
Group    : Development/Tools
License  : MIT
Requires: msrestazure-python = %{version}-%{release}
Requires: msrestazure-python3 = %{version}-%{release}
Requires: adal
Requires: msrest
BuildRequires : adal
BuildRequires : buildreq-distutils3
BuildRequires : msrest

%description
AutoRest: Python Client Runtime - Azure Module
===============================================

%package python
Summary: python components for the msrestazure package.
Group: Default
Requires: msrestazure-python3 = %{version}-%{release}

%description python
python components for the msrestazure package.


%package python3
Summary: python3 components for the msrestazure package.
Group: Default
Requires: python3-core

%description python3
python3 components for the msrestazure package.


%prep
%setup -q -n msrestazure-0.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560272123
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
